
POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "ed44fdee-90f8-44a2-b555-0159511008b2"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "7da9c076-b60c-434c-9bf5-5078fb4d5592",
    "account_id_to": "bdbb70ee-4a69-4098-bf58-536be8ff956b",
    "amount": 1
}